// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type User struct {
	ID        string     `json:"id"`
	Email     string     `json:"email"`
	UserID    *string    `json:"userId"`
	FirstName *string    `json:"firstName"`
	LastName  *string    `json:"lastName"`
	Country   *string    `json:"country"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
}

type UserAuth struct {
	Logged bool    `json:"logged"`
	Token  string  `json:"token"`
	Error  *string `json:"error"`
}

type UserInput struct {
	Email     *string `json:"email"`
	Password  *string `json:"password"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Country   *string `json:"country"`
}

type Users struct {
	Count *int    `json:"count"`
	List  []*User `json:"list"`
}
